return {
	require("vasu.plugins.utils.ai"),
	require("vasu.plugins.utils.autopair"),
	require("vasu.plugins.utils.centered"),
	require("vasu.plugins.utils.flash"),
	require("vasu.plugins.utils.neotree"),
	require("vasu.plugins.utils.markdown"),
	require("vasu.plugins.utils.noice"),
	require("vasu.plugins.utils.mini"),
	require("vasu.plugins.utils.git"),
	require("vasu.plugins.utils.highlight-colors"),
	require("vasu.plugins.utils.session"),
	require("vasu.plugins.utils.snacks"),
	require("vasu.plugins.utils.telescope"),
	-- require("vasu.plugins.utils.showkeys"),
	require("vasu.plugins.utils.ts-autotag"),
	require("vasu.plugins.utils.undotree"),
	require("vasu.plugins.utils.yazi"),
}
