-- lua/vasu/plugins/ui/nvchad.lua

-- NvChad components require some initialization
-- We need to load the highlights from the cache

local status_base46, base46 = pcall(require, "base46")
if not status_base46 then return end

-- Load base46 highlights
-- These are generated by base46 and stored in the cache
local function load_highlights()
	local cache_dir = vim.g.base46_cache
	if vim.fn.isdirectory(cache_dir) == 0 then vim.fn.mkdir(cache_dir, "p") end

	local files = vim.fn.readdir(cache_dir)
	if #files == 0 then
		-- Compile if cache is empty
		pcall(function() require("base46").compile() end)
		files = vim.fn.readdir(cache_dir)
	end

	for _, plugin in ipairs(files) do
		dofile(cache_dir .. plugin)
	end
end

-- Initialize base46 if cache doesn't exist or we want to force compile
-- For now, we assume base46 handles its own compilation when required
-- but we ensure the highlights are loaded.
pcall(load_highlights)

-- Setup NvChad UI components
local status_ui, ui = pcall(require, "nvchad")
if status_ui then
	-- Any additional NvChad UI setup can go here
	-- Usually, NvChad UI works by just being loaded
	-- and looking at the 'chadrc' file.
end

-- Keymaps for NvChad features
vim.keymap.set("n", "<leader>ct", function()
	require("nvchad.themes").open {
		style = "flat", -- flat/rounded/bordered
	}
end, { desc = "NvChad Theme Switcher" })

vim.keymap.set("n", "<leader>ch", "<cmd>NvCheatsheet<CR>", { desc = "NvChad CheatSheet" })

-- Minty (color picker & shades)
vim.keymap.set("n", "<leader>cp", "<cmd>Huefy<CR>", { desc = "Minty Color Picker" })
vim.keymap.set("n", "<leader>cs", "<cmd>Shades<CR>", { desc = "Minty Color Shades" })


-- ── NvChad Terminal ──────────────────────────────────────────────────────────
-- (Disabled in favor of native terminal splits in keymaps.lua)
-- local term = require "nvchad.term"
-- vim.keymap.set({ "n", "t" }, "<leader>tt", function() term.toggle { pos = "float", id = "floatTerm" } end, { desc = "Toggle float terminal" })
-- vim.keymap.set({ "n", "t" }, "<leader>th", function() term.toggle { pos = "sp", id = "hterm" } end, { desc = "Toggle horizontal terminal" })
-- vim.keymap.set({ "n", "t" }, "<leader>tv", function() term.toggle { pos = "vsp", id = "vterm" } end, { desc = "Toggle vertical terminal" })

