-- lua/vasu/plugins/ui/nvchad.lua

-- NvChad components require some initialization
-- We need to load the highlights from the cache

local status_base46, base46 = pcall(require, "base46")
if not status_base46 then return end

-- Load base46 highlights
-- These are generated by base46 and stored in the cache
local function load_highlights()
	local cache_dir = vim.g.base46_cache
	if vim.fn.isdirectory(cache_dir) == 0 then vim.fn.mkdir(cache_dir, "p") end

	local files = vim.fn.readdir(cache_dir)
	if #files == 0 then
		-- Compile if cache is empty
		pcall(function() require("base46").compile() end)
		files = vim.fn.readdir(cache_dir)
	end

	for _, plugin in ipairs(files) do
		dofile(cache_dir .. plugin)
	end
end

-- Initialize base46 if cache doesn't exist or we want to force compile
-- For now, we assume base46 handles its own compilation when required
-- but we ensure the highlights are loaded.
pcall(load_highlights)

-- Setup NvChad UI components
local status_ui, ui = pcall(require, "nvchad")
if status_ui then
	-- Any additional NvChad UI setup can go here
	-- Usually, NvChad UI works by just being loaded
	-- and looking at the 'chadrc' file.
end

-- Keymaps for NvChad features
vim.keymap.set("n", "<leader>ht", function()
	require("nvchad.themes").open {
		style = "flat", -- flat/rounded/bordered
	}
end, { desc = "NvChad [T]heme [H]istory / Switcher" })

vim.keymap.set("n", "<leader>ch", "<cmd>NvCheatsheet<CR>", { desc = "NvChad [C]heat[H]sheet" })

-- Minty (color picker & shades)
vim.keymap.set("n", "<leader>cp", "<cmd>Huefy<CR>", { desc = "Minty [C]olor [P]icker" })
vim.keymap.set("n", "<leader>cs", "<cmd>Shades<CR>", { desc = "Minty [C]olor [S]hades" })

-- NvZone Menu (context menu)
vim.keymap.set("n", "<leader>m", function() require("menu").open "default" end, { desc = "NvChad Context [M]enu" })

-- Right-click context menu
vim.keymap.set({ "n", "v" }, "<RightMouse>", function()
	require("menu.utils").delete_old_menus()
	vim.cmd.exec '"normal! \\<RightMouse>"'

	local pos = vim.fn.getmousepos()
	local buf = vim.api.nvim_win_get_buf(pos.winid)
	local ft = vim.bo[buf].ft

	local options = ft == "neo-tree" and "neo-tree" or "default"
	require("menu").open(options, { mouse = true })
end, { desc = "Context Menu (Right Click)" })
